keybinds:
  # Mode Selection
  letter_mode: "1"
  word_mode: "2"
  gesture_mode: "3"
  mouse_control: "m"
  face_detection: "f"
  toggle_detection_mode: "e"

  # UI Controls
  toggle_fps: "tab"
  toggle_performance: "p"
  toggle_recording: "r"
  help_menu: "h"
  exit: "esc"

  # Training Controls
  quit_training: "q"
  start_stop_recording: "s"
  new_label: "n"
  retrain_label: "r"
  info_display: "i"
  start_training: "t"

  # Camera Test Controls
  save_image: "s"
  reset_camera: "r"
  quit_test: "q"

modes:
  letter:
    enabled: true
    description: "Translate sign language letters"

  word:
    enabled: true
    description: "Translate sign language words"

  gesture:
    enabled: true
    description: "Recognize and translate gestures"

  mouse:
    enabled: true
    description: "Control mouse with hand gestures"

  face:
    enabled: true
    submodes:
      - mesh
      - iris
      - recognition
    description: "Face detection and recognition"

performance:
  target_fps: 30
  enable_threading: true
  enable_gpu: true
  optimize_resolution: true
  notification_duration: 3.0 # seconds

training:
  max_samples_per_label: 1000
  window_size:
    width: 1280
    height: 720
  confidence_threshold: 0.5
  model_complexity: 1

camera_test:
  window_size:
    width: 1280
    height: 720
  save_directory: "test_images"
